---
#- name: Enable EPEL-repo
#  become: yes
#  yum:
#    name: epel-release
#    update_cache: yes
#    state: latest
#  when: ansible_os_family == "RedHat"

- name: "Set timezone (Stockholm is default)"
  become: yes
  timezone:
    name: "{{ basic.timezone | default(basic_default.timezone) }}"

- name: Install vanliga verktyg (YUM)
  become: yes
  yum:
    name: "{{ basic.package_to_install | default(basic_default.package_to_install) }}"
    state: present
  when: ansible_os_family == "RedHat"
  
  # Set (httpd_can_network_connect) flag on and keep it persistent across reboots
- name: Install libsemanage to fix selinux in ansible (YUM)
  become: yes
  yum:
    name: "libsemanage-python"
    state: present
  when: ansible_os_family == "RedHat"

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  become: yes
  selinux:
    policy: targeted
    state: permissive
